Resources:
  UserDynamoTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: Retain
    Properties:
      TableName: '${self:custom.awsResourcePrefix}User'
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
        - AttributeName: Sk
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
        - AttributeName: Sk
          KeyType: RANGE
      Tags:
        - Key: '${self:custom.modules.awsBackup.tag.dynamodb.Key}'
          Value: '${self:custom.modules.awsBackup.tag.dynamodb.Value}'
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  IdempotenceProcessDynamoTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: Retain
    Properties:
      TableName: '${self:custom.awsResourcePrefix}IdempotenceProcess'
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: TTL
        Enabled: true
      Tags:
        - Key: '${self:custom.modules.awsBackup.tag.dynamodb.Key}'
          Value: '${self:custom.modules.awsBackup.tag.dynamodb.Value}'
