version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - yarn
  build:
    commands:
      - npx eslint
      - yarn test
      - npx sls deploy deploy:ap-northeast-1:${DEPLOY_ENV} --verbose
