name: '${self:custom.awsResourcePrefix}graphql'
authentication:
  type: API_KEY # AMAZON_COGNITO_USER_POOLS
# if using CognitoUserPool
#   config:
#     userPoolId: !Ref CognitoUserPool
# additionalAuthentications:
#   - type: API_KEY
apiKeys:
  - name: apiKey
schema: 'appsync/schema.graphql'
caching:
  behavior: PER_RESOLVER_CACHING
  ttl: 3600
  type: 'SMALL'
logging:
  loggingRoleArn: { Fn::GetAtt: [AppSyncLoggingServiceRole, Arn] }
  level: ALL
  excludeVerboseContent: false
# pipelineFunctions:
#   - ${file(./appsync/pipelineFunctions.yml)}
resolvers:
  - ${file(./appsync/resolvers.yml)}
dataSources:
  - ${file(./appsync/datasources.yml)}
