Resources:
  # If WAF is not required, comment out accordingly
  # Waf logs bucket
  AppSyncWebACLBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub aws-waf-logs-${self:custom.awsResourcePrefix}appsync
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  IPWhiteList:
    Type: AWS::WAFv2::IPSet
    Properties:
      Name: Custom-IpAddress-whitelist
      Scope: REGIONAL
      IPAddressVersion: IPV4
      Addresses: '${self:custom.modules.wafv2.wafIpWhiteList.${self:provider.stage}}'

  ### If there are multiple targets, duplicate the following resources (AWS::WAFv2::WebACL,AWS::KinesisFirehose::DeliveryStream) for the number of targets
  ## Be sure to enable Logging after deployment
  # WebACL
  AppSyncWebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: AppSyncWebACL
      DefaultAction:
        Allow: {}
      Description: WebACL for AppSync
      Scope: REGIONAL
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        MetricName: AppSyncWebACL
        SampledRequestsEnabled: false
      Rules:
        - Name: Custom-IpAddress-WhiteList
          Priority: 100
          Statement:
            IPSetReferenceStatement:
              Arn: !GetAtt IPWhiteList.Arn
          Action:
            Allow: {}
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: Custom-IpAddress-WhiteList
            SampledRequestsEnabled: false
        - Name: AWS-AWSManagedRulesCommonRuleSet
          Priority: 200
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          OverrideAction:
            Count: {}
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesCommonRuleSet
            SampledRequestsEnabled: false
        - Name: AWS-AWSManagedRulesKnownBadInputsRuleSet
          Priority: 300
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesKnownBadInputsRuleSet
          OverrideAction:
            Count: {}
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesKnownBadInputsRuleSet
            SampledRequestsEnabled: false
        - Name: AWS-AWSManagedRulesAnonymousIpList
          Priority: 400
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesAnonymousIpList
              ScopeDownStatement:
                NotStatement:
                  Statement:
                    IPSetReferenceStatement:
                      Arn: !GetAtt IPWhiteList.Arn
          OverrideAction:
            Count: {}
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesAnonymousIpList
            SampledRequestsEnabled: false

  # WAF LoggingConfiguration to S3
  AppSyncWafLogConfig:
    Type: AWS::WAFv2::LoggingConfiguration
    Properties:
      ResourceArn: !GetAtt AppSyncWebACL.Arn
      LogDestinationConfigs:
        - !GetAtt AppSyncWebACLBucket.Arn
