- name: '${self:custom.awsResourcePrefix}graphql'
  authenticationType: API_KEY # AMAZON_COGNITO_USER_POOLS
  schema: 'appsync/schema.graphql'
  caching:
    behavior: PER_RESOLVER_CACHING
    ttl: 3600
    type: 'SMALL'
  # if using CognitoUserPool
  # userPoolConfig:
  #   defaultAction: ALLOW
  #   userPoolId: !Ref CognitoUserPool
  logConfig:
    loggingRoleArn: { Fn::GetAtt: [AppSyncLoggingServiceRole, Arn] }
    level: ALL
    excludeVerboseContent: false
  mappingTemplatesLocation: appsync/resolvers
  functionConfigurationsLocation: appsync/resolvers
  functionConfigurations:
    - ${file(./appsync/functionConfigurations.yml)}
  mappingTemplates:
    - ${file(./appsync/mappingtemplates.yml)}
  dataSources:
    - ${file(./appsync/datasources.yml)}
